url: "http://blog.orinr.in"
baseurl: ""
destination: ../orinrin.github.io
title: おりんりんのブログ
description: 一緒に永遠に眠りましょう～
permalink: /:categories/:year/:month/:day/:title/
post_dirs: true
email: nyaa@orinr.in
markdown: kramdown 
